name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clear
      run: make CLEAN
    - name: make_test
      run: make build_test
    - name: run
      run: ./SAT51_TEST

